/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Message } from './message';
import { User } from './user';

export class Chat {
    'name'?: string;
    'members'?: Set<User>;
    'messages'?: Set<Message>;
    'encryptionKey'?: Array<string>;
    'id'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "members",
            "baseName": "members",
            "type": "Set<User>"
        },
        {
            "name": "messages",
            "baseName": "messages",
            "type": "Set<Message>"
        },
        {
            "name": "encryptionKey",
            "baseName": "encryptionKey",
            "type": "Array<string>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Chat.attributeTypeMap;
    }
}

