/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Chat } from './chat';
import { User } from './user';

export class InvitationId {
    'invited'?: User;
    'chat'?: Chat;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "invited",
            "baseName": "invited",
            "type": "User"
        },
        {
            "name": "chat",
            "baseName": "chat",
            "type": "Chat"
        }    ];

    static getAttributeTypeMap() {
        return InvitationId.attributeTypeMap;
    }
}

