/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class LoginResponse {
    'result'?: LoginResponse.ResultEnum;
    'sessionID'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "result",
            "baseName": "result",
            "type": "LoginResponse.ResultEnum"
        },
        {
            "name": "sessionID",
            "baseName": "sessionID",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return LoginResponse.attributeTypeMap;
    }
}

export namespace LoginResponse {
    export enum ResultEnum {
        Verified = <any> 'VERIFIED',
        OnCooldown = <any> 'ON_COOLDOWN',
        WaitingArea = <any> 'WAITING_AREA',
        Unsuccessfull = <any> 'UNSUCCESSFULL',
        Blocked = <any> 'BLOCKED'
    }
}
