/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Chat } from './chat';

export class User {
    'id'?: string;
    'displayName': string;
    'chats'?: Set<Chat>;
    'profilePictureId'?: string;
    'hash': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "chats",
            "baseName": "chats",
            "type": "Set<Chat>"
        },
        {
            "name": "profilePictureId",
            "baseName": "profilePictureId",
            "type": "string"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }
}

